---
---
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=us-ascii" />

  <title>{{ page.title }} | IPCVS</title>
  <meta http-equiv="Content-Type" content="text/html; charset=us-ascii" />
  <link type="text/css" rel="stylesheet" media="all" href="/assets/site.css" />
  <!--[if IE]>
	<link type="text/css" rel="stylesheet" media="all" href="/sites/all/themes/zen/zen/ie.css?B" />
  <![endif]-->
  <script src="/assets/cufon-yui.js" type="text/javascript"></script>
  <script src="/assets/fonts.js" type="text/javascript"></script>
  <script type="text/javascript">
    Cufon.replace('#site-name strong a', { fontFamily: 'Handel Gothic' });
    Cufon.replace('#site-slogan', { fontFamily: 'Handel Gothic' });
	Cufon.replace('#content-header h1.title', { fontFamily: 'Handel Gothic' });
	Cufon.replace('#primary ul li a span', { fontFamily: 'Handel Gothic' });
	Cufon.replace('#footer-message', { fontFamily: 'Handel Gothic' });
	Cufon.replace('#content-area div.content h3', { fontFamily: 'Handel Gothic' });	
  </script>
</head>

<body class="front not-logged-in node-type-page one-sidebar sidebar-left">
  <div id="page">
    <div id="page-inner">
      <a name="top" id="navigation-top"></a>

      <div id="skip-to-nav">
        <a href="#navigation">Skip to Navigation</a>
      </div>

      {% include header.html %}

      <div id="main">
        <div id="main-inner" class="clear-block with-navbar">
          <div id="content">
            <div id="content-inner">
              <div id="content-header">
                <h1 class="title">{{ page.title }}</h1>
              </div><!-- /#content-header -->

              <div id="content-area">
                <div id="node-1" class="node node-type-page">
                  <div class="node-inner">
                    <div class="content">
                      {{ content }}
                    </div>
                  </div>
                </div><!-- /node-inner, /node -->
              </div>
            </div>
          </div><!-- /#content-inner, /#content -->

          <div id="navbar">
            <div id="navbar-inner" class="clear-block region region-navbar">
              <a name="navigation" id="navigation"></a>

              <div id="primary">
                <ul class="links">
                  <li class="first active"><a href="/" title="Home"><span class="link">Home</span></a></li>

                  <li><a href="/content/services" title="Services"><span class="link">Services</span></a></li>

                  <li><a href="/content/portfolio" title="Portfolio"><span class="link">Portfolio</span></a></li>

                  <li><a href="/content/references" title="References"><span class="link">References</span></a></li>

                  <li><a href="/content/contact" title="Contact"><span class="link">Contact</span></a></li>
                </ul>
              </div><!-- /#primary -->
            </div>
          </div><!-- /#navbar-inner, /#navbar -->

          <div id="sidebar-left">
            <div id="sidebar-left-inner" class="region region-left">
              <div id="block-views-rotating_page_image-block_2" class=
              "block block-views region-odd odd region-count-1 count-1">
                <div class="block-inner">
                  <div class="content">
                    <div class=
                    "view view-rotating-page-image view-id-rotating_page_image view-display-id-block_2 view-dom-id-1">
                    <div class="view-content">
                        <div class=
                        "views-row views-row-1 views-row-odd views-row-first views-row-last">
                        <div class="views-field-field-image-fid">
                            <span class="field-content"><img src=
                            "/assets/images/content{{ page.contentimage }}.jpg" alt="" title="" class=
                            "imagecache imagecache-image_right_rotating imagecache-default imagecache-image_right_rotating_default"
                            width="270" height="203" /></span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div><!-- /block-inner, /block -->
            </div>
          </div><!-- /#sidebar-left-inner, /#sidebar-left -->
        </div>
      </div><!-- /#main-inner, /#main -->

	  {% include footer.html %}
     
    </div>
  </div><!-- /#page-inner, /#page -->
  <!-- To avoid delays, initialize Cufón before other scripts at the bottom -->
  <script type="text/javascript"> Cufon.now(); </script>
</body>
</html>


